"""Add todo for todolist

Revision ID: e96c79e32af4
Revises: be04c5e1c6d7
Create Date: 2016-09-03 20:49:20.947427

"""

# revision identifiers, used by Alembic.
revision = 'e96c79e32af4'
down_revision = 'be04c5e1c6d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('isdone', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_created'), 'todos', ['created'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_created'), table_name='todos')
    op.drop_table('todos')
    ### end Alembic commands ###
